# Generated by Django 3.1 on 2021-05-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETHUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('gasprice_rapid', models.IntegerField()),
                ('gasprice_fast', models.IntegerField()),
                ('gasprice_standard', models.IntegerField()),
                ('gasprice_slow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_power_on', models.BooleanField()),
                ('gpu_temp', models.IntegerField()),
                ('realtime_hashrate', models.FloatField()),
                ('accepted_hashrate', models.FloatField()),
                ('lifetime_earning', models.FloatField()),
                ('costs', models.IntegerField()),
            ],
        ),
    ]
